# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 02:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, help_text='A description of the disease.')),
                ('primary_inheritance', models.CharField(choices=[('AR', 'AR: Autosomal recessive'), ('AD', 'AD: Autosomal dominant'), ('XLR', 'XLR: X-linked recessive'), ('XLD', 'XLD: X-linked dominant'), ('XL', 'XL: X-linked'), ('YL', 'YL: Y-linked'), ('MI', 'MI: Mitochondrial'), ('SM', 'SM: Somatic')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ens_gene', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Please provide a valid Ensembl gene identifier', regex='(?P<ens_gene>ENSG[0-9]{11})')], verbose_name='Ensembl gene identifier')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Gene name')),
                ('chromosome', models.CharField(max_length=2)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
